NetCamp/NetCamp/Models/Entities/Ogrenci.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NetCamp.Models.Entities
{
    public class Ogrenci
    {
        public long Id { get; set; }
        [Required]//boş geçilemez 
        [MaxLength(10,ErrorMessage = "Kullanıcı Adı maksimum 10 karakter olabilir")]
        [MinLength(3,ErrorMessage ="Kullanıcı Adı minimum 3 karakter olabilir")]
        public string KullaniciAdi { get; set; }
        public string Password { get; set; }
        [Required]
        public string Adi { get; set; }
        [Required]
        public string Soyadi { get; set; }
        public int Yasi { get; set; }
    }
}

NetCamp/NetCamp/Models/ErrorViewModel.cs
using System;

namespace NetCamp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NetCamp/NetCamp/Models/GlobalData.cs
using NetCamp.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCamp.Models
{
    public static class GlobalData
    {
        public static List<Ogrenci> Ogrenciler { get; set; }
    }
}

NetCamp/NetCamp/Models/Services/OgrenciServisi.cs
using NetCamp.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NetCamp.Models.Services
{
    public class OgrenciServisi
    {
        public OgrenciServisi()
        {
            if (GlobalData.Ogrenciler==null)
            {
                GlobalData.Ogrenciler = new List<Ogrenci>();
                GlobalData.Ogrenciler.Add(new Ogrenci { Adi = "Admin", Id = 1, KullaniciAdi = "Admin", Password = "123", Soyadi = "Admin", Yasi = 1 });
            }
        }
        public List<Ogrenci> GetList()
        {
           return GlobalData.Ogrenciler;
        }
        public Ogrenci Get(long id)
        {
            return GlobalData.Ogrenciler.FirstOrDefault(q=>q.Id==id);
        }



        public Ogrenci Insert(Ogrenci model)
        {
            model.Id=DateTime.Now.Ticks;
            GlobalData.Ogrenciler.Add(model);
            return model;
        }
        public Ogrenci Update(Ogrenci model)
        {
            var data = GlobalData.Ogrenciler.FirstOrDefault(q => q.Id == model.Id);
            var index = GlobalData.Ogrenciler.IndexOf(data);
            GlobalData.Ogrenciler[index] = model;
            return model;
        }

        public bool Delete(long id)
        {
            var data = GlobalData.Ogrenciler.FirstOrDefault(q => q.Id == id);
            var index = GlobalData.Ogrenciler.IndexOf(data);
            GlobalData.Ogrenciler.RemoveAt(index);
            return true;
        }
    }
}

NetCamp/NetCamp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetCamp.Models;

namespace NetCamp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NetCamp/NetCamp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using NetCamp.Models.Entities;

namespace NetCamp.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if ()
            {

            }
            base.OnActionExecuting(context);
        }
        public IActionResult Index()
        {
            return View(new Ogrenci());
        }

        [HttpPost]
        public IActionResult Index(Ogrenci model)
        {

            return View();
        }
        public IActionResult Erisilemez()
        {
            return View(new Ogrenci());
        }
    }
}

NetCamp/NetCamp/Controllers/OgrenciController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetCamp.Models.Entities;
using NetCamp.Models.Services;

namespace NetCamp.Controllers
{
    public class OgrenciController : Controller
    {
        OgrenciServisi servis;
        public OgrenciController(OgrenciServisi _servis)
        {
            servis = _servis;
        }
        public IActionResult List()
        {
            return View(servis.GetList());
        }
        public IActionResult Insert()
        {
            return View(new Ogrenci());
        }

        [HttpPost]
        public IActionResult Insert(Ogrenci model)
        {
            if (!ModelState.IsValid)
            {
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        ViewBag.Error = error.ErrorMessage;
                    }
                }
                return View(model);
            } 
            else
            {
               servis.Insert(model);
               return RedirectToAction("List");
            }
           
        }

        //action üzerinde route tanımı yaparken aynı isme sahip diğer actionlarda etkinlenir
        //[Route("/ogrenci-guncelle/{ogrenciId}")]
        public IActionResult Update(long ogrenciId)
        {
            return View(servis.Get(ogrenciId));
        }
         
        [HttpPost]
        public IActionResult Update(Ogrenci model)
        {
            if (!ModelState.IsValid)
            {
                foreach (var modelState in ModelState.Values)
                {
                    foreach (var error in modelState.Errors)
                    {
                        ViewBag.Error = error.ErrorMessage;
                    }
                }
                return View(model);
            }
            else
            {
                servis.Update(model);
                return RedirectToAction("List");
            }

        }

        public IActionResult Delete(long id)
        {
            var sonuc = servis.Delete(id);
            return RedirectToAction("List");
        }
        // https://github.com/turgutumectaze/netcamp
    }
}

NetCamp/NetCamp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NetCamp/NetCamp/Views/Login/Erisilemez.cshtml
@{
    ViewData["Title"] = "Erisilemez";
}

<h1>Erisilemez</h1>

NetCamp/NetCamp/Views/Login/Index.cshtml
@model Ogrenci

@{
    ViewData["Title"] = "Öğrenci Ekleme Formu";
}

<h1>
    Öğrenci Formu
    <a class="btn btn-info btn-float-right" asp-controller="Ogrenci" asp-action="List">Geri</a>
</h1>

<form asp-controller="Ogrenci" asp-action="Insert">
    <div class="form-group">
        <label>Kullanıcı Adı</label>
        @*@Html.TextBox("Adi")*@
        @Html.TextBoxFor(q => q.KullaniciAdi, new { @class = "form-control" })
        @*<input name="KullaniciAdi" id="KullaniciAdi" class="form-control" required />*@
    </div>
    <div class="form-group">
        <label>Adı</label>
        @Html.TextBoxFor(q => q.Adi, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Soyadı</label>
        @Html.TextBoxFor(q => q.Soyadi, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Yası</label>
        @Html.TextBoxFor(q => q.Yasi, new { @class = "form-control" })
    </div>
    @*<div class="form-group">
            @Html.TextAreaFor(q => q.KullaniciAdi, new { @class = "form-control" })
        </div>*@
    <button type="submit" class="btn btn-primary">Kaydet</button>
    <p>@ViewBag.Error</p>
</form>

NetCamp/NetCamp/Views/Ogrenci/Insert.cshtml
@model Ogrenci

@{
    ViewData["Title"] = "Öğrenci Ekleme Formu";
}

<h1>Öğrenci Formu 
    <a class="btn btn-info btn-float-right" asp-controller="Ogrenci" asp-action="List">Geri</a></h1>

<form asp-controller="Ogrenci" asp-action="Insert">
    <div class="form-group">
        <label>Kullanıcı Adı</label>
        @*@Html.TextBox("Adi")*@
        @Html.TextBoxFor(q => q.KullaniciAdi, new { @class = "form-control" })
        @*<input name="KullaniciAdi" id="KullaniciAdi" class="form-control" required />*@
    </div>
    <div class="form-group">
        <label>Adı</label>
        @Html.TextBoxFor(q => q.Adi, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Soyadı</label>
        @Html.TextBoxFor(q => q.Soyadi, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Yası</label>
        @Html.TextBoxFor(q => q.Yasi, new { @class = "form-control" })
    </div>
    @*<div class="form-group">
        @Html.TextAreaFor(q => q.KullaniciAdi, new { @class = "form-control" })
    </div>*@
    <button type="submit" class="btn btn-primary">Kaydet</button>
    <p>@ViewBag.Error</p>
</form>

NetCamp/NetCamp/Views/Ogrenci/List.cshtml
@model List<NetCamp.Models.Entities.Ogrenci>
@{
    ViewData["Title"] = "Öğrenci Listesi";
}

<h1>Öğrenci Listesi <a class="btn btn-info float-right" asp-controller="Ogrenci" asp-action="Insert">Ekle</a></h1>

<table>
    <tr>
        <td>Id</td>
        <td>Ad Soyad</td>
        <td>Yaş</td>
        <td>İşlem</td>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Adi @item.Soyadi</td>
            <td>@item.Yasi</td>
            <td>
                <a class="btn btn-info" asp-controller="Ogrenci" asp-action="Update" asp-route-ogrenciId="@item.Id">Güncelle</a>

                <a class="btn btn-danger" asp-controller="Ogrenci" asp-action="Delete" asp-route-id="@item.Id">Sil</a>
            </td>
        </tr>
    }
</table>

NetCamp/NetCamp/Views/Ogrenci/Update.cshtml
@model Ogrenci

@{
    ViewData["Title"] = "Öğrenci Güncelleme Formu";
}

<h1>
    Öğrenci Formu
    <a class="btn btn-info btn-float-right" asp-controller="Ogrenci" asp-action="List">Geri</a>
</h1>

<form asp-controller="Ogrenci" asp-action="Update">
    @Html.HiddenFor(q=>q.Id)
    <div class="form-group">
        <label>Kullanıcı Adı</label>
        @Html.TextBoxFor(q => q.KullaniciAdi, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Adı</label>
        @Html.TextBoxFor(q => q.Adi, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Soyadı</label>
        @Html.TextBoxFor(q => q.Soyadi, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Yası</label>
        @Html.TextBoxFor(q => q.Yasi, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-primary">Kaydet</button>
    <p>@ViewBag.Error</p>
</form>

NetCamp/NetCamp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetCamp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NetCamp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogrenci" asp-action="List">Öğrenci Listesi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - NetCamp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>